# Generated by Django 4.0.4 on 2022-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='main.course'),
        ),
    ]
