# Generated by Django 4.1.1 on 2022-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0007_alter_course_preview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(max_length=50),
        ),
    ]
